# Security-Konfiguration
security:
    # Passwort-Hashing-Algorithmus (Argon2 für Sicherheit)
    password_hashers:
        App\Entity\User:
            algorithm: auto

    # Provider für Benutzerauthentifizierung
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout
                # Wohin umleiten nach Logout
                target: app_login

    # Zugriffsregeln
    access_control:
        # Login-Seite für alle zugänglich
        - { path: ^/login, roles: PUBLIC_ACCESS }
        # Admin-Bereich nur für Administratoren
        - { path: ^/admin, roles: ROLE_ADMIN }
        # Alle anderen Seiten für eingeloggte Benutzer
        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # Schnellere Hashes für Tests
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'plaintext'
