version: '3.8'
services:
  app:
    build: .
    container_name: symfony_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      - SYMFONY_ENV=dev
    depends_on:
      - db
  web:
    image: nginx:alpine
    container_name: symfony_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  db:
    image: mariadb:latest
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kpi_tracker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
